### ISSUE TITLE
Request to add a new calcium imaging analysis tool

### ISSUE THREAD

**Issue by CaelynCheung1996** [bahanonu/imaging_tools#3]
Hi Biafra, I'm a PhD student at Bioengineering UIUC. I would also like to have my work with Dr. Landsness on "Automated sleep state classification of wide-field calcium imaging data via multiplex visibility graphs and deep learning" (https://doi.org/10.1016/j.jneumeth.2021.109421) be listed here as a calcium imaging analysis tool. The code is available at https://github.com/comp-imaging-sci/MVG-CNN.  We also release our wide-field calcium imaging data in sleep on PhysioNet at https://physionet.org/content/calcium-imaging-sleep-state/1.0.0/. Please let me know if you need additional information.

**Comment by bahanonu** [comment]
Awesome, thanks for the heads up; I'll give the paper a look and I'll update the table soon. If you have a preferred one sentence description, I can use that in the `Notes` column.

**Comment by CaelynCheung1996** [comment]
Thanks for having our work on the table! The notes can be “Automated sleep states classification using multiplex visibility graphs and deep learning”.  XiaohuiFrom: Biafra AhanonuSent: Monday, November 29, 2021 5:52 PMTo: bahanonu/imaging_toolsCc: Xiaohui Zhang; AuthorSubject: Re: [bahanonu/imaging_tools] Request to add a new calcium imaging analysis tool (Issue #3) Awesome, thanks for the heads up; I'll give the paper a look and I'll update the table soon. If you have a preferred one sentence description, I can use that in the Notes column.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by CaelynCheung1996** [comment]
> Awesome, thanks for the heads up; I'll give the paper a look and I'll update the table soon. If you have a preferred one sentence description, I can use that in the `Notes` column.

Thanks for having our work on the table! The note can be “Automated sleep states classification using multiplex visibility graphs and deep learning”.
